feature: sprint 9, spring boot init version
PusIan/java-filmorate pull request #2
Opened 2023-04-12 22:45 UTC by PusIan

2023-04-13 05:00 UTC, EugeneLenkevich requested changes
Привет, Руслан, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-04-14 06:32 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/request/UserRequestDto.java
> +        if (name == null || name.isBlank()) {
Спасибо, добавил!

2023-04-14 06:35 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
> +        return conversionService.convert(films.get(id), FilmResponseDto.class);
Аннотацию @slf4j применил. По поводу логгирования, реализовал через plugin: 
		<!--logging-->
		<dependency>
			<groupId>org.zalando</groupId>
			<artifactId>logbook-spring-boot-starter</artifactId>
			<version>2.14.0</version>
		</dependency>
Логгирует все rest api запросы, запрос/ответ.
Пример:
2023-04-14 09:34:22.736 TRACE 7866 --- [nio-8080-exec-2] org.zalando.logbook.Logbook              : {"origin":"remote","type":"request","correlation":"d48d66c9f12e5382","protocol":"HTTP/1.1","remote":"0:0:0:0:0:0:0:1","method":"POST","uri":"http://localhost:8080/users","host":"localhost","path":"/users","scheme":"http","port":"8080","headers":{"accept":["*/*"],"accept-encoding":["gzip, deflate, br"],"connection":["keep-alive"],"content-length":["101"],"content-type":["application/json"],"host":["localhost:8080"],"postman-token":["09b68f89-b868-46ae-a7ed-3a94a8097373"],"user-agent":["PostmanRuntime/7.31.3"]},"body":{"login":"dolore","name":"Nick Name","email":"mail@mail.ru","birthday":"1946-08-20"}}
2023-04-14 09:34:22.827 TRACE 7866 --- [nio-8080-exec-2] org.zalando.logbook.Logbook              : {"origin":"local","type":"response","correlation":"d48d66c9f12e5382","duration":130,"protocol":"HTTP/1.1","status":200,"headers":{"Connection":["keep-alive"],"Content-Type":["application/json"],"Date":["Fri, 14 Apr 2023 06:34:22 GMT"],"Keep-Alive":["timeout=60"],"Transfer-Encoding":["chunked"]},"body":{"id":1,"email":"mail@mail.ru","login":"dolore","name":"Nick Name","birthday":"1946-08-20"}}

2023-04-14 06:53 UTC, PusIan commented
> Привет, Руслан, спасибо за PR
> 
> В целом все отлично :) Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-04-14 06:58 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
> +        return conversionService.convert(films.get(id), FilmResponseDto.class);
Ну эта штука логирует http-запросы, тут же скорее речь про логирование именно бизнес-логики. Потом у нас бизнес-логика переедет в сервисные классы, там это разделение станет понятнее, пока ок, пусть так будет

2023-04-14 08:26 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

PS

на счет плейсхолдеров
два примера
log.debug("что то происходит: {}", someValue)
log.debug("что то происходит: " + someValue)

допустим у нас установлен уровень логирования INFO, то есть выше чем debug. В случае если у нас будут использваны плейсхолдеры, то в метод они будут переданы, но далее ничего не произойдет. А вот если мы конкатенируем строки, то они будут складываться каждый раз независимо от уровня логирования, плюс все параметры к строке приводится, надеюсь понятно почему. В общем, использование плейсхолдеров менее ресурсоемко :)

2023-04-14 08:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/web/handler/RestResponseEntityExceptionHandler.java
> +        logger.error("Not found error: " + ex.getMessage());
А зачем так, с плейсхолдерами было ж лучше :)

2023-04-14 17:43 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/handler/RestResponseEntityExceptionHandler.java
> +        logger.error("Not found error: " + ex.getMessage());
Спасибо, про placeholder ясно!

Почему так сделал:
После того, как я убрал явное создание логгера, поменялся интерфейс логгинга с:
package org.slf4j;
на
package org.apache.commons.logging;
в котором методов, работающих с placeholder нет, и я не долго думая сделал конкатенацию )
Кстати в моем случае даже аннотация не нужна, логгер доступен.
![image](https://user-images.githubusercontent.com/49454056/232113290-0081b886-c127-4a07-ab86-f142f269e4f9.png)

2023-04-14 17:48 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/handler/RestResponseEntityExceptionHandler.java
> +        logger.error("Not found error: " + ex.getMessage());
Создав явно - инстанцировал объект с интерфейсом: org.slf4j;
Видимо вот эта зависимость:
        <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>logbook-spring-boot-starter</artifactId>
            <version>2.14.0</version>
        </dependency>
создаёт логгер неявно и используется интерфейс: org.apache.commons.logging по умолчанию.

2023-04-14 17:55 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/handler/RestResponseEntityExceptionHandler.java
> +        logger.error("Not found error: " + ex.getMessage());
метод: error(Object message, Throwable t) не стал вызывать так как сохраняет весь стек, захламляет лог. Надо всех пересадить на один интерфейс slf4j, попробую к следующей сдаче )

2023-04-27 18:01 UTC, merged

2023-04-30 07:41 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/handler/RestResponseEntityExceptionHandler.java
> +        logger.error("Not found error: " + ex.getMessage());
For information: разобрался, аннотация @Slf4j инстанцирует объект с именем log. Я ошибочно использовал логгер с именем logger, который неявно присутствует в каждом объекте spring через пакет: spring-jcl.