feature: sprint 10, reorganize structure, add likes, add friends
PusIan/java-filmorate pull request #3
Opened 2023-04-29 23:51 UTC by PusIan

2023-04-30 13:12 UTC, EugeneLenkevich requested changes
Привет, Руслан , спасибо за PR

В целом все отлично, интересный подход с иерархией классов, только давай еще проверим как обязанности распределены по слоям, оставил несколько коментариев, посмотри, пожалуйста, соседние места :)

По классике обязанности распределяются вот так

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2023-04-30 13:12 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> likes = new HashSet<>();
А что если во множестве хранить ссылку на другуе сущности, а не их ид, проще ж потом работать с ними будет вроде как :)

2023-04-30 13:12 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        this.userStorage.validateId(userId)
validateId  - не совсем понятно каким именно образом хранилище будет валидировать ид-шник, да и должно ли оно этим занматься, а что если заменить на метод хранилища, например, exists, который будет проверять есть ли в хранилище запись с таким id? :)

2023-04-30 13:12 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparing(film -> -film.getLikes().size()))
Выборка данных и сортировка - это все таки обязанность хранилища, давай все операции выборки, сортировки и пр данных будем производить в хранилище, в сервисах у нас пусть содержится бизнес-логика, то есть логика предметной области :)

2023-04-30 13:12 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(friendsForOtherUser::contains)
Фильтрация - тоже обязанность хранилица :)

2023-05-01 20:04 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        this.userStorage.validateId(userId)
Спасибо, реализовал через existsById.

2023-05-01 20:10 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparing(film -> -film.getLikes().size()))
Поместил весь метод в FilmStorage, в  FilmService на данный момент просто wrapper над методом из FilmStorage.

2023-05-01 20:31 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> likes = new HashSet<>();
Спасибо, на данный момент существенных преимуществ для хранения вместо id - ссылки на объект - не вижу.

2023-05-01 20:32 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(friendsForOtherUser::contains)
Если считать, что будем использовать например postgres, то можно весь запрос вынести в FilmStorage,
реляционное ханилице умеет возвращать пересечение (select ... intersect select ...), тогда пересечение множеств будет решаться средствами СУБД, хотя для большей масштабируемости, чем больше берёт на себя service тем лучше (СУБД - сложнее масштабируется). Вынес весь запрос в FilmStorage, генерацию исключений оставляю на роль сервиса.

2023-05-01 20:43 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        this.userStorage.validateId(userId)
Но добавил wrapper на existsById в CrudService:
    void validateIds(int... entityIds) {
        for (int entityId : entityIds) {
            if (!this.getStorage().existsById(entityId)) {
                throw getNoDataFoundException(entityId);
            }
        }
    }

2023-05-02 02:54 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(friendsForOtherUser::contains)
Тут основная идея в том, что до проблемы масштабируемости надо еще дорасти, а вот простота поддерживаемости кода актуальна всегда :)

2023-05-02 02:55 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-05-02 09:34 UTC, merged