8 developed features
PusIan/java-filmorate pull request #30
Opened 2023-06-12 05:42 UTC by PusIan

2023-06-13 03:50 UTC, EugeneLenkevich requested changes
Привет, Руслан, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmSearchBy.java
> +    title,
значения enum обычно с большой буквы делают, давай так же сделаем
TITLE
DIRECTOR

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                        return FilmSearchBy.valueOf(s);
Думаю проще поставить FilmSearchBy как тип переменной, прямо начиная с контроллера. Если извне передадут неверное значение, то запрос просто не пройдет. Ну или мапить в котроллере а в сервис отдавать уже enum. Тогда не нужны будут такие проверки :)

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> review = reviewStorage.getById(reviewId);
Review review = reviewStorage.getById(reviewId).orElseThrow(()-> NotFoundException("Review with id " + reviewId + " not found.") )

Чутка покороче :)

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBFilmStorage.java
> +        if (year.isPresent()) {
А не получится ли сразу это сделать в едином sq-запросе? Можно к самой строке запроса добавлять условие

Иначе, из-за того что в запросе стоит limit, возможны ситуации когда запрос вообще ничего не вернет при том что в БД записи будут (не проверял, но вероятность есть :)

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBFilmStorage.java
> +        if (year.isPresent()) {
yearOptional.ifPresent(year-> {
///тут у нас уже нормальная переменная year
})

Можно с optional еще работать вот так :)

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBFilmStorage.java
> +    public List<Film> filmsDirectorSorted(int directorId, String sort) {
String sort

У нас же вроде есть специальный enum-чик, может его тут использовать :)

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
> +                .stream()
.stream()
                .map(film -> conversionService.convert(film, FilmResponseDto.class))
                .collect(Collectors.toList());

Можно метод сделать для конверси в dto, чтобы избавиться от дублирования кода :)

2023-06-13 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/ReviewController.java
> +    public Review create(@Valid @RequestBody Review review) {
Соседний контроллер возвращает dto, этот же - сущности. Лучше чтобы было или так или так, как именно не важно, главное чтобы единообразно :)

2023-06-13 10:19 UTC, gyngazov commented
в RecommendServiceImpl
в методе prepareDiffFreqMatrices
там двойной цикл по мапе diff, он у тебя внутри двойного цикла
он должен быть наруже 
https://web.archive.org/web/20100126002457/http://www.daniel-lemire.com/fr/documents/publications/SlopeOne.java

2023-06-13 18:51 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                        return FilmSearchBy.valueOf(s);
+

2023-06-13 18:52 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> review = reviewStorage.getById(reviewId);
+

2023-06-13 18:53 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBFilmStorage.java
> +    public List<Film> filmsDirectorSorted(int directorId, String sort) {
Enum был под другую задачу, добавили

2023-06-13 19:07 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
> +                .stream()
+

2023-06-13 20:30 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/ReviewController.java
> +    public Review create(@Valid @RequestBody Review review) {
+

2023-06-13 21:11 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBFilmStorage.java
> +    public List<Film> filmsDirectorSorted(int directorId, String sort) {
Правда пришлось конвертер писать, так как в нижнем регистры параметры не маппятся на enum (которые в верхнем регистре). Собственно поэтому мы и делали в нижнем регистре )

2023-06-13 21:11 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmSearchBy.java
> +    title,
+

2023-06-13 21:11 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmSearchBy.java
> +    title,
Написаны кастомные конвертеры, для поддержки параметров в нижнем регистре

2023-06-13 22:15 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBFilmStorage.java
> +        if (year.isPresent()) {
да, хорошая идея, спасибо!

2023-06-13 22:30 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/ReviewController.java
> +    public Review create(@Valid @RequestBody Review review) {
Спасибо за ревъю

2023-06-14 03:10 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBFilmStorage.java
> +    public List<Film> filmsDirectorSorted(int directorId, String sort) {
public enum SortBy {
 TITLE ("title desc")

 private String term; 
}

2023-06-14 03:16 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

PS

а еще можно было для сортировки
1. добавить строковое поле в enum, что то типа такого
public enum SortBy {
TITLE ("title desc");

private String term;
}
2. или же сделать мапу в которую сложить соответствие  enum и нужной строки. Или, вообще, для каждого значения enum написать свой метод-обработчик, который дописывает нужный кусок sql и точно так же сложить в map :)

2023-07-04 17:43 UTC, merged