feature: add database h2, alpha version, postman tests are working
PusIan/java-filmorate pull request #7
Opened 2023-05-23 22:33 UTC by PusIan

2023-05-27 12:09 UTC, EugeneLenkevich requested changes
Привет, Руслан, спасибо за PR

Интересная работа, все отлично, но пару совсем небольших моментиков отметил  :)

2023-05-27 12:09 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
Data - хитрая аннотация, генерирует equals по всем полям

Хэш-код берем от самого экземпляра класса, а в сравнении участвует id :)

Вообще такой момент. Сущность - это не просто объект, а представление строки таблицы БД, которую однозначно определяет идентификатор.  Две сущности будут относится к одной и той же строке в таблице если у них будет один и тот же идентификатор. Хотя, физически, это могут быть разные объекты (то есть переменные будут ссылаться на разные объекты в памяти) и у них даже могут различаться остальные поля. Например мы одновременно имеем несколько версий одной и той же записи, но с разными полями (сущность до и  сущность после редактирования).

В общем, equals и hashCode лчше генерить руками на основании id

2023-05-27 12:09 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBUserStorage.java
> +        if (existsById(id)) {
А не проще сразу вытаскивать запись, если ее нет то будет просто пустой набор данных :) Или так делать обязательно по какой то причине?

2023-05-27 12:09 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/WriteService.java
> +    abstract Storage<T> getStorage();
И давай все таки private не будет забывать для полей :)

2023-05-27 19:16 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
Попробую использовать след аннотацию:
@EqualsAndHashCode(callSuper = true, of = {"id"})

2023-05-27 19:17 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBUserStorage.java
> +        if (existsById(id)) {
Согласен, код короче! Переделал, спасибо!

2023-05-27 19:17 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/service/WriteService.java
> +    abstract Storage<T> getStorage();
+

2023-05-27 19:19 UTC, PusIan commented
> Привет, Руслан, спасибо за PR
> 
> Интересная работа, все отлично, но пару совсем небольших моментиков отметил :)

Спасибо, Евгений, как всегда полезные комментарии.

2023-05-27 19:23 UTC, PusIan commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
На самом деле у меня с id возможно путанница, я объявил id и на уровне главной сущности, и на уровне дочерних сущностей. Сделал это чтобы конструктор по аннотации @AllArgsConstructor создал мне конструктор с id в том числе (проблематично заставить lombok добавить атрибуты родительского класса). А такая иерархия мне нужна, что строить иерархию сервис классов например. Что подскажешь? Как вариант самому определить конструктор и включить все атрибуты дочернего объекта и родительского.

2023-05-28 03:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
> Попробую использовать след аннотацию: @EqualsAndHashCode(callSuper = true, of = {"id"})

Этого более чем достаточно.

Ну а в случае нседования можно и ручками конструктор обьявить,ничего страшного. Вообще, обычно для сущностей определяется базовый суперкласс с полями типа id createdAt updatedAt и пр и все от него наследуются

2023-05-28 03:08 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-05-30 16:01 UTC, merged